name: Tests

on:
  push:
    branches:
      - dev
      - main

jobs:
  hello-world:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello world
        run: echo "Welcome to the Github Actions workshop!"

  unit-test:
    runs-on: ubuntu-20.04
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run unit-tests
        run: make tests_run > unit-test-results.txt
      - name: Run coverage
        run: make coverage > coverage-results.txt
      - name: Upload coverage outputs
        uses: actions/upload-artifact@v3
        with:
          name: coverage_outputs
          path: coverage-results.txt
          if-no-files-found: ignore

  functional-test:
    runs-on: ubuntu-20.04
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run functional tests
        run: make functional_tests > functional-test-results.txt
      - name: Upload functional test outputs
        uses: actions/upload-artifact@v3
        with:
          name: function-tests_outputs
          path: functional-test-results.txt
